### ISSUE TITLE
loser is not inclusive

### ISSUE THREAD

**Issue by abeepbeepsheep** [squi-ddy/7up-discord-bot#4]
pls fix sir i should be told that i am bad at this game in at least 20 different languages and dialects.
include more terms for loser like
"Still a five letter word starting with los and ending in er"
and "Squiddy!"
fix or i want my refund 😡 👎 0️⃣

**Comment by squi-ddy** [comment]
random loser messages is a good idea
but why personal attack
i am so sad
🤣 🤣

**Comment by abeepbeepsheep** [comment]
i am sorry for personal attack
i will not ad astra next time 😢

**Comment by squi-ddy** [comment]
smh its ad hominem attack get your facts straight
